/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarearedes;

import java.awt.Color;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Luis Rojas
*/

public class Cliente extends javax.swing.JFrame {
    
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        this.getContentPane().setBackground(Color.green);
        this.setResizable(false);
        ImageIcon poti= new ImageIcon(getClass().getResource("poti.jpg"));
        ImageIcon icono = new ImageIcon(poti.getImage().getScaledInstance(foto_perfil.getWidth(), foto_perfil.getHeight(), Image.SCALE_DEFAULT));
        foto_perfil.setIcon(icono);
        this.setTitle("CHAT CLIENTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        area_mensaje = new javax.swing.JTextArea();
        enviar_mensaje = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        texto_mensaje = new javax.swing.JTextField();
        foto_perfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        area_mensaje.setColumns(20);
        area_mensaje.setRows(5);
        jScrollPane1.setViewportView(area_mensaje);

        enviar_mensaje.setText("Enviar");
        enviar_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviar_mensajeActionPerformed(evt);
            }
        });

        jLabel1.setText("JAIME POTS TORRICO");

        texto_mensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_mensajeActionPerformed(evt);
            }
        });

        foto_perfil.setText("foto_perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(texto_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enviar_mensaje))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foto_perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviar_mensaje)
                    .addComponent(texto_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviar_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviar_mensajeActionPerformed
        // TODO add your handling code here:
        try{
        String mensaje_saliente = "";
        mensaje_saliente = texto_mensaje.getText().trim();
        dout.writeUTF(mensaje_saliente);
        area_mensaje.setText(area_mensaje.getText().trim()+"\nYO CLIENTE: "+mensaje_saliente);
        //CON ESTO AGREGO EL TEXTO MIO TAMBIEN A LA VENTANA DEL CHAT
        }catch(Exception e){
            //COSAS DE EXCEPCIONES
        }
        texto_mensaje.setText("");
    }//GEN-LAST:event_enviar_mensajeActionPerformed

    private void texto_mensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_mensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_mensajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
        
        try{
            s = new Socket("127.0.0.1",1201); 
            //IP ES DIRECCION LOCAL PORQUE CLIENTE Y SERVIDOR CORREN EN MISMO EQUIPO
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());
            String mensaje_entrante="";
            while(!mensaje_entrante.equals("TERMINAR CHAT")){
                mensaje_entrante = din.readUTF();
                area_mensaje.setText(area_mensaje.getText().trim()+"\nSERVIDOR dice: "+mensaje_entrante);
                
            }
                
        }catch(Exception e){
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextArea area_mensaje;
    private javax.swing.JButton enviar_mensaje;
    private javax.swing.JLabel foto_perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField texto_mensaje;
    // End of variables declaration//GEN-END:variables
}
